#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("St_Josephs.Droid.Resource", IsApplication=true)]

namespace St_Josephs.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::St_Josephs.Droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::St_Josephs.Droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::St_Josephs.Droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::St_Josephs.Droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::St_Josephs.Droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::St_Josephs.Droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::St_Josephs.Droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::St_Josephs.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::St_Josephs.Droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::St_Josephs.Droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::St_Josephs.Droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::St_Josephs.Droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::St_Josephs.Droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::St_Josephs.Droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::St_Josephs.Droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::St_Josephs.Droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int fab_colorDisabled = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int fab_colorNormal = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int fab_colorPressed = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int fab_colorRipple = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fab_shadow = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int fab_size = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int color_action_bar = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int darker_action_bar = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int fab_material_blue_500 = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int fab_elevation_lollipop = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int fab_scroll_threshold = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int fab_shadow_size = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int fab_size_mini = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_size_normal = 2131034115;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int android_support_v7_widget_CardView2 = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int mini = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int notepad = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int settings = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Notepad = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int AppTheme = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int Mono_Android_Theme_Splash = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int NotepadTheme = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] FloatingActionButton = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
