#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("St_Josephs.Droid.Resource", IsApplication=true)]

namespace St_Josephs.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::St_Josephs.Droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::St_Josephs.Droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::St_Josephs.Droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::St_Josephs.Droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::St_Josephs.Droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::St_Josephs.Droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::St_Josephs.Droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::St_Josephs.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::St_Josephs.Droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::St_Josephs.Droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::St_Josephs.Droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::St_Josephs.Droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::St_Josephs.Droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::St_Josephs.Droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::St_Josephs.Droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::St_Josephs.Droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::St_Josephs.Droid.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0001
			public const int items = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int times = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int cardBackgroundColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int cardCornerRadius = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int cardElevation = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int cardMaxElevation = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int cardPreventCornerOverlap = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int cardUseCompatPadding = 2130771992;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f01001a
			public const int contentPadding = 2130771994;
			
			// aapt resource value: 0x7f01001e
			public const int contentPaddingBottom = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int contentPaddingLeft = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int contentPaddingRight = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int contentPaddingTop = 2130771997;
			
			// aapt resource value: 0x7f010021
			public const int fab_colorDisabled = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int fab_colorNormal = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int fab_colorPressed = 2130771999;
			
			// aapt resource value: 0x7f010022
			public const int fab_colorRipple = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int fab_shadow = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int fab_size = 2130772004;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000a
			public const int cardview_dark_background = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int cardview_light_background = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int cardview_shadow_end_color = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int cardview_shadow_start_color = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int color_action_bar = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int common_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int darker_action_bar = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int fab_material_blue_500 = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_compat_inset_shadow = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_default_elevation = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_default_radius = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int fab_elevation_lollipop = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int fab_scroll_threshold = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int fab_shadow_size = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int fab_size_mini = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int fab_size_normal = 2131230723;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fab_shadow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int fab_shadow_mini = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_add_white_24dp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_search_white_24dp = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int monoandroidsplash = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0005
			public const int adjust_height = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int adjust_width = 2131492870;
			
			// aapt resource value: 0x7f0c0008
			public const int android_support_v7_widget_CardView2 = 2131492872;
			
			// aapt resource value: 0x7f0c000a
			public const int fab = 2131492874;
			
			// aapt resource value: 0x7f0c0000
			public const int hybrid = 2131492864;
			
			// aapt resource value: 0x7f0c000d
			public const int inside = 2131492877;
			
			// aapt resource value: 0x7f0c0009
			public const int map = 2131492873;
			
			// aapt resource value: 0x7f0c0007
			public const int mini = 2131492871;
			
			// aapt resource value: 0x7f0c0001
			public const int none = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int normal = 2131492866;
			
			// aapt resource value: 0x7f0c000b
			public const int notepad = 2131492875;
			
			// aapt resource value: 0x7f0c0003
			public const int satellite = 2131492867;
			
			// aapt resource value: 0x7f0c000c
			public const int settings = 2131492876;
			
			// aapt resource value: 0x7f0c0004
			public const int terrain = 2131492868;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Map = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Notepad = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PictureTake = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int main_menu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int map = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int notepad = 2131427330;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050023
			public const int app_name = 2131034147;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int common_android_wear_notification_needs_update_text = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_text = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int common_android_wear_update_title = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_api_unavailable_text = 2131034141;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_button = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_enable_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_enable_title = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_button = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_install_text_phone = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_text_tablet = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_invalid_account_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_invalid_account_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_needs_enabling_title = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_network_error_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_network_error_title = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_needs_update_title = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_notification_ticker = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_sign_in_failed_text = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_sign_in_failed_title = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_unknown_issue = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unsupported_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_unsupported_title = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_button = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_text = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_update_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_updating_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_updating_title = 2131034130;
			
			// aapt resource value: 0x7f05001c
			public const int common_open_on_phone = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int common_signin_button_text = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int common_signin_button_text_long = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hello = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090003
			public const int AppTheme = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int CardView = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int CardView_Dark = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int CardView_Light = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int MapTheme = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int Mono_Android_Theme_Splash = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int NotepadTheme = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Settings = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] FloatingActionButton = new int[] {
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
